networks:
  mynet:
    driver: bridge

services:
  webserver:
    build: .
    ports: 
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
    links:
      - db_club:db_club
    networks:
      mynet:
  
  db_club:
    build: ./sql/
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: club
      MYSQL_USER: client
      MYSQL_PASSWORD: senha_da_nasa
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    networks:
      mynet:
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db_club:db_club
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 200M
    networks:
      mynet: